spring.application.name=demo

openai.api.key=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
spring.data.mongodb.uri=mongodb://localhost:27017/medsecure

